### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#1318]
![image (2)](https://user-images.githubusercontent.com/44737332/109579276-76c92200-7b5d-11eb-8f72-335c52c7815c.png)

Looks like the contact form isn't working. 
If it is more than a very quick job, I'm happy for this to simply be changed to:

> To get in touch with the EA Hub Resources team email Catherine at catherine@eahub.org.
> 
> We would love to have more community members contribute to the EA Hub Resources. To add resources, make suggestions for changes, or join our team, read our information on how to contribute.

**Comment by sebgrebe** [comment]
Fixed, netlify had changed their webpage's URLs from .com to .app
