### ISSUE TITLE
Scaling down two first images in the "Guidelines on Depicting Poverty"

### ISSUE THREAD

**Issue by marcinkowrygo** [rtcharity/resources.eahub.org#257]

**Comment by taymonbeal** [comment]
By "scaling down", you mean we're currently using an image file with larger dimensions than is actually displayed on the site, and you want to replace it with a smaller one to save bandwidth? Or the image is being displayed wrong?

**Comment by sebgrebe** [comment]
I think it was about width & height.

**Comment by taymonbeal** [comment]
As in, the *user-visible* width and height on the page?

**Comment by sebgrebe** [comment]
yes
