### ISSUE TITLE
Make "Contact LEAN" a contact form

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/resources.eahub.org#268]
Let's switch from a mailto: link to a proper contact form

**Comment by sebgrebe** [comment]
Made a pull request: https://github.com/rtcharity/resources.eahub.org/pull/282

Big issue: I implemented this using zapier, which receives the POST request from the user's form input and sends an email to whichever email address we want. Problem is that this is only free up to 100 emails per month. All the services like this that I could find cost money.
I will get an alert if we get close to our limit, in which case we could change back to emails (not ideal).

**Comment by taymonbeal** [comment]
I commented on the PR.
