### ISSUE TITLE
Formatting requests

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#443]
- [x]  Make large image centre aligned

The next ones are based on the category (in this case I was working on Start an EA Group). I'm thinking that the categories should look close to what the articles look like now. I think I might have suggested the other way around before sorry! The next four suggestions might immediately resolve when that changes. 

- [x] Have the title larger , and each of the headings smaller than they currently are, and left aligned.  E.g. Title = 32pt purple, h1= 24 black h2 = 18 pt purple, h3 = 14 pt black. (text can be 11pt I think). However whatever the articles look like would be fine (still want a san-serif font though). 

- [x] Have the width of the text bounded, like it is in the articles in the current resources page. 

- [x] Make the hyperlinks green, with pale green underlined mouse over (like the current articles).    

- [x] Bullet points (in the current category the bullet points don't appear.

BUT the thing I would like differently to how the articles are now is:

- [x] text in a bullet point should stay the same size as regular paragraphs.

**Comment by sebgrebe** [comment]
This should all be done now. Please let me know if I missed/misunderstood anything
