### ISSUE TITLE
Home page and menu edits

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#451]
- [x] Align content in the resources part of the hamburger menu
![screenshot_20190916-125041](https://user-images.githubusercontent.com/44737332/64930135-d0faf800-d881-11e9-82c6-d6b9e8ca1ba1.png)

- [ ] Fix strange arrow/scroll thingee that appears on a small screen (appears on my desktop, but not on my phone.

![image](https://user-images.githubusercontent.com/44737332/64930140-dc4e2380-d881-11e9-805d-76cc1285516a.png)

- [x] In the Menu, make "Resources" go to the resources home page (currently there is no way to go back to the resource home page on the menu except for using the hamburger).

- [x] Add a new category - Graphics. This will go at the end after events. Hopefully that doesn't mess everything up!

- [x] Make home page deeper, by 
1. Putting the two LEARN and TAKE ACTION on one row under the title "Resources for Aspiring Effective Altruists:", and the other four in two rows under the title "Resources for Running EA Groups".

2. Making the images larger. Probably twice the width would be good if possible. Use these images:
https://drive.google.com/drive/folders/1p9190J-vWrEtbnUj7soZiv6-rIGjG6XZ?usp=sharing

3. Making the footer go at the bottom of the page.  (It would be good if this happened for all the pages too - but once the content is on, there probably won't be a problem with the current set up except for the home page). 
![home page](https://user-images.githubusercontent.com/44737332/64930242-0ce28d00-d883-11e9-8e90-ba9f115eb7e6.png)

- [x] I'd quite like to add a link to "contact us" in the top text (description) - but I don't seem to be able to. Perhaps there could be a text field instead of the description just before the logos.

- [x] On the menu, put a space between between EA Hub / and Resources so that it's evenly positioned.

**Comment by Richenda** [comment]
>Make a space (rather than a /) between EA Hub and Resources in the menu bar

This is an intentional stylistic choice, so I don't want that changed.

**Comment by cafelow** [comment]
The slash is okay - but the Resources should definitely link to the resources page.

**Comment by cafelow** [comment]
Actually @Richenda I'm not sure the slash works in this case. I understand for profiles and groups because the URL is actually a slash. But that isn't the case for resources. If you feel strongly about it we can keep it, but I don't think it makes sense stylistically unless there is something I'm missing here.

**Comment by Richenda** [comment]
It is part of the design. It is a style issue, and if we drop it for this we drop it everywhere. I’m product designer for the Hub, so this isn’t something that is really part of your domain.

**Comment by Richenda** [comment]
There’s also some other stylistic stuff that needs to be fixed from what I can see. Perhaps I should write up a guide and talk it over.

**Comment by cafelow** [comment]
No worries. We can keep the slash. I'm on a pretty tight timeline for having a live site on the 26th (as requested by Michal), so perhaps we can talk about design after that. I have had to make some changes to menus etc to fit the different structure of the resources, which is different to the current structure.

**Comment by Richenda** [comment]
Yeh that sounds good. I’ve been trying to pin him down for a meeting. I’ll be able to communicate better after that!

**Comment by Richenda** [comment]
And yep the menu changes are completely fine but I want to make sure icons aren’t duplicated too much. I can source more. But that can be sorted later.

**Comment by cafelow** [comment]
Oh yes. The icons will be different - I think Seb just threw those ones on as place holders.

**Comment by sebgrebe** [comment]
> Fix strange arrow/scroll thingee that appears on a small screen (appears on my desktop, but not on my phone.

@cafelow I can't replicate this. Can you tell me the browser and the width?

**Comment by sebgrebe** [comment]
> Putting the two LEARN and TAKE ACTION on one row under the title "Resources for Aspiring Effective Altruists:", and the other four in two rows under the title "Resources for Running EA Groups".

Are you sure about this? The structure is also 3-levels deep with the deepest level not being shown in the menus. This adds a fourth level at the top (LEARN/TAKE ACTION), which also won't be seen in the menus. Personally, I find this confusing

**Comment by sebgrebe** [comment]
> Making the images larger. Probably twice the width would be good if possible. Use these images:
https://drive.google.com/drive/folders/1p9190J-vWrEtbnUj7soZiv6-rIGjG6XZ?usp=sharing

Done

**Comment by sebgrebe** [comment]
> Making the footer go at the bottom of the page. (It would be good if this happened for all the pages too - but once the content is on, there probably won't be a problem with the current set up except for the home page).

This is - for reasons ;) - a bit tricky to do. But because we've enlarged the icons, we shouldn't run into this issue on any page, including the home page

**Comment by cafelow** [comment]
> > Putting the two LEARN and TAKE ACTION on one row under the title "Resources for Aspiring Effective Altruists:", and the other four in two rows under the title "Resources for Running EA Groups".
> 
> Are you sure about this? The structure is also 3-levels deep with the deepest level not being shown in the menus. This adds a fourth level at the top (LEARN/TAKE ACTION), which also won't be seen in the menus. Personally, I find this confusing. Also, the way it looks right now the design is closer to the Hub's. With those subheadings it moves away from it

Oh, sorry, I wasn't clear. The idea is not for the menu to show this, but just for the home page body to have this information. 
![image](https://user-images.githubusercontent.com/44737332/65079947-543c5b00-d9f4-11e9-9f71-a5d54479f198.png)

**Comment by cafelow** [comment]
>Making the images larger. Probably twice the width would be good if possible. Use these images:
> https://drive.google.com/drive/folders/1p9190J-vWrEtbnUj7soZiv6-rIGjG6XZ?usp=sharing

@sebgrebe  Can you change the images for Learn and Tips to match the files in the drive. Thanks!

**Comment by cafelow** [comment]
> @cafelow I can't replicate this. Can you tell me the browser and the width?
The above screenshot was Chrome on Windows 10 - width of around 650 pixels (I think) or less (e.g. when I split the screen between two windows).
It looks even funkier on Firefox:
![image](https://user-images.githubusercontent.com/44737332/65088331-10a21b00-da0d-11e9-80db-b6bde7d89d0a.png)

**Comment by sebgrebe** [comment]
> > @cafelow I can't replicate this. Can you tell me the browser and the width?
> 
> The above screenshot was Chrome on Windows 10 - width of around 650 pixels (I think) or less (e.g. when I split the screen between two windows).
> It looks even funkier on Firefox:
> ![image](https://user-images.githubusercontent.com/44737332/65088331-10a21b00-da0d-11e9-80db-b6bde7d89d0a.png)

Hm, not sure what's going on there. I can reproduce this, even on this width (I have a Mac though). 650px is a really weird width for desktop, I don't think we should cater for that anyway. I'll try at work tomorrow (have a windows laptop there), but I would de-prioritise this

**Comment by sebgrebe** [comment]
If you're ok with my [last comment](https://github.com/rtcharity/resources.eahub.org/issues/451#issuecomment-534252030), this ticket can be closed, @cafelow. Feel free to do so yourself
