### ISSUE TITLE
Change title font size

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#460]
- [ ] Please make the title font the same size as h1 is now (it is currently slightly smaller than h1. I think the same size will still look titley because it is bold.

**Comment by sebgrebe** [comment]
Not sure what you mean. Do you mean *article* titles? They're 36px. So is the title on the landing page.

**Comment by cafelow** [comment]
Yes, article or section titles. But actually they appear to be the same size now (perhaps I was a bit crosseyed before).
