### ISSUE TITLE
Moving menu?

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#461]
Okay so this is probably asking the impossible, but I thought I'd ask just in cases. 

Some of the pages are quite long, and the menu stays at the top. If it IS easy to make the menu travel down the page with you that would be really cool. But if it isn't easy please delete this issue!

**Comment by sebgrebe** [comment]
Nope, that's 2 lines of CSS :) (As luck would have it, I worked on a similar problem at work a while ago)
