### ISSUE TITLE
Home Page Edits

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#530]
- [x] Put "Start an EA Group" back on to the main part of the page with this icon - https://drive.google.com/open?id=1h-VH60O9ZVf4eyHoOU-Bgo67HMvpevXR (I went to change the icon in the dev page, which somehow resulted in the icon and "Start an EA Group" link disappearing entirely. 

- [ ] Change the top text to read 

"On this site you will find helpful information, guides, tips and downloads, whether you want to learn more as an individual or as an EA Group. This site is a work in progress, if you want to help us improve the site please contact us" (with a link to contact us). 

- [x] Change text below the "Learn" and "Take Action" icons to 
"Resources for EA Groups"

- [x] On the menu add a space between "EA Hub" and "/ Resources"

**Comment by sebgrebe** [comment]
> Change the top text to read
I'll leave that as an exercise for you, @cafelow, you can do this [here](https://confident-minsky-f713d6.netlify.com/admin/#/collections/pages/entries/home) now
