### ISSUE TITLE
Teach Catherine how to solve small image issue

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#534]
I'd like to be able to force each small image into a new paragraph. 

![image](https://user-images.githubusercontent.com/44737332/65468499-59981a80-deb8-11e9-810d-33a932cbec56.png)

**Comment by sebgrebe** [comment]
I've added a new class for block images to the [example article](https://confident-minsky-f713d6.netlify.com/events/articles/example-article/)
