### ISSUE TITLE
Signup button is shown when I'm already logged in

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/resources.eahub.org#609]
![image](https://user-images.githubusercontent.com/14195560/65721997-924c1580-e0ab-11e9-842e-92c27d12d78b.png)

**Comment by sebgrebe** [comment]
this was always the case, can't really do anything about this unless resources is fully integrated into hub app

**Comment by cafelow** [comment]
I'd be personally keen to delete the "Sign Up" button from resources until when/if it is integrated. @Richenda what do you think?

**Comment by sebgrebe** [comment]
@cafelow fine by me as "My profile" leads to login page if someone is not already logged in

**Comment by cafelow** [comment]
Okay, so the conclusion is to delete both sign up and my profile buttons, and we can always add them back in later.

**Comment by sebgrebe** [comment]
@cafelow  

Alternatively, we leave "My Profile", which would lead a user that's not signed in to the sign in page? Seems ok to me, and we'd still have some connection to authentication on the Hub (which is nice as it could create more traffic to the hub, maybe even to people signing up who aren't yet).

**Comment by cafelow** [comment]
Okay, sounds good. So conclusion - leave "my profile", and delete "Sign up".

**Comment by sebgrebe** [comment]
Done
