### ISSUE TITLE
Can't update text on home page! 

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#627]
Seb - you set this for me as an exercise and I forgot! Turns out it isn't happy unless I put an image in (which I suspect would stuff up the home page). 

![image](https://user-images.githubusercontent.com/44737332/65728225-66ae4700-e10e-11e9-8ae2-3fd7afb539d0.png)

The text I was planning on putting in was:

On this site you will find helpful information, guides, tips and downloads about effective altruism, whether you want to learn more as an individual or as an EA Group. This site is a work in progress, if you want to help us improve the site please [contact us](/contact-lean/).

**Comment by sebgrebe** [comment]
Added correct content and removed images requirement for home page
