### ISSUE TITLE
Video playback error

### ISSUE THREAD

**Issue by laderhold** [rtcharity/resources.eahub.org#641]
https://resources.eahub.org/learn/about-ea/ All of the embedded videos on this page won't play. For instance: "An error occurred. Please try again later. (Playback ID: zHmSkvXhsJcZNyo1)
Learn More"

I wasn't sure if this is an "admin issue", since it is using an embedded player.

I am able to search youtube for the talk and play them, for instance this link for the first one:
https://www.youtube.com/watch?v=WyprXhvGVYk
and this for the second one:
https://www.youtube.com/watch?v=LtWINl3C_7s

Not sure about the third one, but I think it's this one:
https://www.youtube.com/watch?v=1xsR0XBwyo4

**Comment by sebgrebe** [comment]
Thanks, the links were merely dummy links.
I've added the actual links (went with the one @laderhold suggested for the third one, but I am not sure myself whether it's the intended one).

Note to admins: Videos must be "embeddable", which for youtube links means that the "embed" occurs in the link. For example, the third link is actually https://www.youtube.com/embed/1xsR0XBwyo4
