### ISSUE TITLE
Change facebook preview information in preparation for sharing. 

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#644]
![image](https://user-images.githubusercontent.com/44737332/66363411-ad3f5380-e9e2-11e9-89ce-8c846aa19c74.png)

 - It would be good if the preview text instead said something consice. e.g. "Information, guides, tips and downloads about effective altruism for individuals and EA groups".

- The preview image should be replaced too. The second image in the scroll isn't bad, but it would be best if it appeared first, and ideally had the green backgroup.

This seems like a good source for information: https://developers.facebook.com/docs/sharing/webmasters

**Comment by sebgrebe** [comment]
Done: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fresources.eahub.org%2F
