### ISSUE TITLE
Improvements to the side menu

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#649]
We are having a few menu issues
- [x] It would be good to have the menu remain open with the section you are looking at (e.g. If you are looking at "Start an EA group" it would be good for the side menu to have that part of the menu stay open and ideally highlight the section that you are on (that may be problematic since we also have articles, but perhaps when you are in an article it could just not highlight anything, or ideally highlight the section that the article is linked off).

The other issue is getting the drop down menu easy to click - at the moment it is difficult to click as the arrow is small and the cursor doesn't change when you mouse over. It is also unclear that the category pages have content. 
 
SMALL TEMPORARY FIX
-  [x] Make the down arrow larger and make the cursor change when you mouse over if that is possible. 

REAL FIX
- [ ] Will probably be making the categories on the menu (e.g. "Learn", "Take Action") NOT be linked to a page, but instead make the drop down open. The category pages will be within the drop down and say something like "Overview of "Learn"" (TBD). Liz our website accessibility whizz is going to work out a plan, and then I'll edit this.

**Comment by sebgrebe** [comment]
@cafelow 
Changes I've implemented:
- Icons bigger and section titles being underlined when hovered over 
- Menus are open when articles from it selected and section and categories headings are bold when related content selected

**Comment by sebgrebe** [comment]
@cafelow Any thought on this? Can we close this ticket for now? If you still want the bigger change, maybe we could make a separate ticket for this?
