### ISSUE TITLE
Change formatting of links

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#808]
Could you make the hyperlinks
- Colour HEX: #49776f (they are too light and don't match accessibility guidelines)
- Bold (accessibility guidelines state that colour shouldn't be the only difference between text and links, and Richenda prefers this to underlines).

**Comment by sebgrebe** [comment]
I've changed the colors, not sure making links bold is a good idea. It looks quite "heavy-handed". I think underline looks better and is also a web standard. Boldness implies emphasis, not link.

![Screen Shot 2019-11-12 at 08 22 47](https://user-images.githubusercontent.com/15908208/68654407-c2e5f280-0525-11ea-9bbc-30ba7fe33942.png)

@Richenda @cafelow ?

**Comment by cafelow** [comment]
I like the dark teal - thanks for the fix. 
Fair enough about the bold - I see your point. Okay, I'm making an executive decision to have underlined links as I think that will solve the other problem of it being unclear when there are headings that are links. Can you make that happen please Seb?

**Comment by cafelow** [comment]
Just for the resources BTW.

**Comment by sebgrebe** [comment]
Implemented the underline
