### ISSUE TITLE
Make a nicely styled button

### ISSUE THREAD

**Issue by cafelow** [rtcharity/resources.eahub.org#810]
We can make okay buttons, e.g. `<button onclick="window.location.href = '';">Click Here</button>`
If possible I'd like it to be 
- centered
- rounded corners (but not shaded)
- coloured the new dark teal HEX #49776f
- White text the same size as H3 is now. 

The idea is that we can use these buttons in the pages that have the main purpose of directing people to more pages e.g. "Start a Group" so people can see immediately that these are the places to go to get more info. At the moment we are using headings that are also links, and it is confusing as the colour doesn't make it obvious that it is a link, because it just looks like the headings are coloured differently. I could put the links within regular text, but it isn't so immediately obviously these links are the purpose of the page.

**Comment by sebgrebe** [comment]
The difference between buttons and links is usually that buttons change something on the given page you are (e.g., toggles something currently hidden), whereas a link sends the user to a new page. If we don't have a very good reason for it, I'd hence advice against using buttons for navigation:

> The starkest difference between a link and a button to me is that a link navigates the user to a new resource, taking them away from the current context (internal links are the only wrinkle here). A button toggles something in the interface, like a video player; or triggers new content in that same context, like a popup menu using aria-haspopup.

https://marcysutton.com/links-vs-buttons-in-modern-web-applications

**Comment by cafelow** [comment]
Okay fair call. I'll close this. We can solve this in one fell swoop by just making links underlined, even though it isn't stylish.
